---
# tasks file for programming
# python
- name: Install Python development packages
  become: true
  apt:
    state: present
    name:
      - python3
      - python3-dev 
      - python3-pip 

- name: Install python-is-python3 if on Focal and above
  when: (ansible_facts['lsb']['codename'] == 'focal') or
    (ansible_facts['lsb']['codename'] == 'jammy')
  become: true
  apt:
    state: present
    name:
      - python-is-python3

- name: Install additional packages with pip
  pip:
    name:
      - numpy
      - scipy
      - matplotlib
    state: latest
    executable: pip3

# C++
- name: Install C++ development packages
  become: true
  apt:
    state: present
    name:
      - valgrind
      - clang-format 
      - build-essential 
      - git 
      - cmake 

- name: Install Conan C++ package manager
  pip:
    name:
      - conan
    state: latest
    executable: pip3